### ISSUE TITLE
Sensitive Data Exposure

### ISSUE THREAD

**Issue by iamaldi** [apavlidi/IT_API#49]
Hi @apavlidi ,
Please take a look at the following: 
https://github.com/apavlidi/IT_API/blob/72e02ecba2662ac1d115800eb17419a0add7fbac/configs/ldap.js#L11

Looks like you forgot to remove such sensitive information (mongodb database **password**) from the code when published it to GitHub.

**Comment by apavlidi** [comment]
Thank you for your feedback @iamaldi. Issue resolved at #50.
Closing the issue
