### ISSUE TITLE
GET files/:id/downloadAll 

### ISSUE THREAD

**Issue by h01d** [apavlidi/IT_API#67]
Response code: 502/503

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at api.it.teithe.gr Port 443</address>
</body></html>

**Comment by Avlonitis** [comment]
we need this get fixed ASAP

**Comment by kvisnia** [comment]
Please check if the problem still appears.

**Comment by h01d** [comment]
1 month for 2 minutes of work. Problem fixed.
